# Generated by Django 4.2.5 on 2023-12-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='class_number',
            field=models.CharField(max_length=10),
        ),
    ]
