# Generated by Django 4.2.5 on 2023-12-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_alter_classsection_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='period_name',
            field=models.CharField(choices=[('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3'), ('p4', 'P4'), ('p5', 'P5'), ('p6', 'P6')], max_length=10),
        ),
    ]
