# Generated by Django 4.2.5 on 2023-12-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateConfigMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatereaderid', models.IntegerField(unique=True)),
                ('imei', models.BigIntegerField()),
                ('gatereadername', models.CharField(blank=True, max_length=45, null=True)),
                ('simno', models.BigIntegerField()),
                ('ipaddress', models.CharField(blank=True, max_length=45, null=True)),
                ('ssid', models.CharField(blank=True, max_length=45, null=True)),
                ('subnetmask', models.CharField(blank=True, max_length=45, null=True)),
                ('defaultgateway', models.CharField(blank=True, max_length=45, null=True)),
                ('routerpassword', models.CharField(blank=True, max_length=45, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lang', models.FloatField(blank=True, null=True)),
                ('updatestatus', models.BooleanField(blank=True, null=True)),
                ('updatedts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tblgateconfigmaster',
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('version', models.FloatField()),
                ('signalstength', models.IntegerField()),
                ('tagcount', models.IntegerField()),
                ('gatereaderid', models.IntegerField()),
                ('imei', models.BigIntegerField()),
                ('gatereadername', models.CharField(blank=True, max_length=100, null=True)),
                ('simno', models.BigIntegerField(blank=True, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=45, null=True)),
                ('ssid', models.CharField(blank=True, max_length=45, null=True)),
                ('subnetmask', models.CharField(blank=True, max_length=45, null=True)),
                ('defaultgateway', models.CharField(blank=True, max_length=45, null=True)),
                ('routerpassword', models.CharField(blank=True, max_length=45, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tagdata', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'tblrawdata',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=45)),
                ('siteid', models.CharField(max_length=45)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('enabled', models.BooleanField()),
            ],
            options={
                'db_table': 'tblsiteinfo',
            },
        ),
    ]
